### ISSUE TITLE
Atas das reuniões da comissão de meio ambiente

### ISSUE THREAD

**Issue by Meio-ambiente** [EscolaWaldorfAngelim/Documentos#14]
[Alimentacao galinhas e galos Jardim.docx](https://github.com/user-attachments/files/16019440/Alimentacao.galinhas.e.galos.Jardim.docx)
[Aprendizado - galos e galinhas.docx](https://github.com/user-attachments/files/16019441/Aprendizado.-.galos.e.galinhas.docx)
[ata comissao de meio ambiente 22 de junho de 2023.docx](https://github.com/user-attachments/files/16019442/ata.comissao.de.meio.ambiente.22.de.junho.de.2023.docx)
[ata comissao de meio ambiente 27 fev 24.docx](https://github.com/user-attachments/files/16019443/ata.comissao.de.meio.ambiente.27.fev.24.docx)
[ata da reuniao de 05 de abr 22 - meio ambiente.docx](https://github.com/user-attachments/files/16019444/ata.da.reuniao.de.05.de.abr.22.-.meio.ambiente.docx)
[ata da reuniao de 09 de fevereiro de 2022 - meio ambiente.docx](https://github.com/user-attachments/files/16019445/ata.da.reuniao.de.09.de.fevereiro.de.2022.-.meio.ambiente.docx)
[ata da reuniao de 11 de setembro - meio ambiente.docx](https://github.com/user-attachments/files/16019446/ata.da.reuniao.de.11.de.setembro.-.meio.ambiente.docx)
[ata da reuniao de 23 de outubro - meio ambiente.docx](https://github.com/user-attachments/files/16019447/ata.da.reuniao.de.23.de.outubro.-.meio.ambiente.docx)
[ata da reuniao de 29 de maio - meio ambiente.docx](https://github.com/user-attachments/files/16019448/ata.da.reuniao.de.29.de.maio.-.meio.ambiente.docx)
[ata da reuniao de 29 de outubro - meio ambiente.docx](https://github.com/user-attachments/files/16019449/ata.da.reuniao.de.29.de.outubro.-.meio.ambiente.docx)
[Ata de 06 de abril de 2023 - comissão meio ambiente.docx](https://github.com/user-attachments/files/16019450/Ata.de.06.de.abril.de.2023.-.comissao.meio.ambiente.docx)
[Ata de 13 de abril de 2023 - comissão meio ambiente.docx](https://github.com/user-attachments/files/16019451/Ata.de.13.de.abril.de.2023.-.comissao.meio.ambiente.docx)
[Ata de 16 de março de 2023 - meio ambiente e corpo pedagogico Jardim.docx](https://github.com/user-attachments/files/16019452/Ata.de.16.de.marco.de.2023.-.meio.ambiente.e.corpo.pedagogico.Jardim.docx)
[Ata reuniao da Comissao meio ambiente - 14 Mai.docx](https://github.com/user-attachments/files/16019453/Ata.reuniao.da.Comissao.meio.ambiente.-.14.Mai.docx)
[EWA_Planejamento_Envolvimento_Associativo_2024_Meio ambiente no Jardim.docx](https://github.com/user-attachments/files/16019454/EWA_Planejamento_Envolvimento_Associativo_2024_Meio.ambiente.no.Jardim.docx)

**Comment by EscolaWaldorfAngelim** [comment]
Todos os arquivos estão no repositorio da comissao e esse usuario "meio-ambiente" foi adicionado como Colaborador. Então pode editar paginas da Wiki :)
